/**
 * THIS IS A SERVER COMPONENT
 */

import Header from '@/components/global/Header'
import { poppins, jost } from '@/ui/fonts'
import type { Metadata } from 'next'
import { getServerSession } from 'next-auth'
import SessionProvider from '@/components/global/SessionProvider'
// import { ClerkProvider } from '@clerk/nextjs'
import { headers } from 'next/headers'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession()
  const pathname = headers().get('x-next-pathname') as string
  console.log(pathname)

  // console.log(router, 'router')
  return (
    // <ClerkProvider>
    <html lang="en">
      <body
        className={`${jost.variable} ${poppins.variable} ${
          pathname === '/' ? ' body_b' : ''
        } `}
      >
        <main>
          <SessionProvider session={session}>
            <Header />
            {children}
          </SessionProvider>
        </main>
      </body>
    </html>
    // </ClerkProvider>
  )
}
